apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "external-kong-ingress-controller.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ template "external-kong-ingress-controller.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
