apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name:  {{ template "external-kong-ingress-controller.fullname" . }}
  labels:
    app: {{ template "external-kong-ingress-controller.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ template "external-kong-ingress-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "external-kong-ingress-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
